'use server';
/**
 * @fileOverview An AI design tool to visualize custom rug and crochet kit designs based on user inputs.
 *
 * - visualizeCustomRugDesign - A function that handles the design visualization process.
 * - VisualizeCustomRugDesignInput - The input type for the visualizeCustomRugDesign function.
 * - VisualizeCustomRugDesignOutput - The return type for the visualizeCustomRugDesign function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const VisualizeCustomRugDesignInputSchema = z.object({
  description: z
    .string()
    .describe(
      'A detailed textual description of the desired rug or crochet kit design, including style, colors, patterns, and intended room.'
    ),
});
export type VisualizeCustomRugDesignInput = z.infer<
  typeof VisualizeCustomRugDesignInputSchema
>;

const VisualizeCustomRugDesignOutputSchema = z.object({
  imageUrl: z
    .string()
    .describe(
      "A data URI of the generated image visualizing the custom rug or crochet kit design. Format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  designDescription: z
    .string()
    .describe(
      'An AI-generated description of the visualized design, potentially echoing or elaborating on the input description.'
    ),
});
export type VisualizeCustomRugDesignOutput = z.infer<
  typeof VisualizeCustomRugDesignOutputSchema
>;

export async function visualizeCustomRugDesign(
  input: VisualizeCustomRugDesignInput
): Promise<VisualizeCustomRugDesignOutput> {
  return visualizeCustomRugDesignFlow(input);
}

// This prompt defines the textual instruction for the image generation model.
const visualizeCustomRugDesignPrompt = ai.definePrompt({
  name: 'visualizeCustomRugDesignPrompt',
  input: { schema: VisualizeCustomRugDesignInputSchema },
  // For image generation models like Imagen, the `output` schema here primarily guides
  // the textual response, if any, that accompanies the image. The image itself
  // is obtained from the `media` part of the ai.generate response.
  prompt: `Generate a high-quality, realistic image of a custom rug or crochet kit design. The design should perfectly match the following description:

Description: {{{description}}}

Also, provide a concise textual summary of the generated design in the response.`,
});

const visualizeCustomRugDesignFlow = ai.defineFlow(
  {
    name: 'visualizeCustomRugDesignFlow',
    inputSchema: VisualizeCustomRugDesignInputSchema,
    outputSchema: VisualizeCustomRugDesignOutputSchema,
  },
  async (input) => {
    // Call the image generation model with the prompt text derived from visualizeCustomRugDesignPrompt.
    const { media, text } = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001', // Imagen 4 for text-to-image
      prompt: visualizeCustomRugDesignPrompt(input), // The string generated by the prompt template
    });

    if (!media || !media.url) {
      throw new Error('Failed to generate image for the custom design.');
    }

    // Imagen models often provide minimal text output. If text is empty, fall back to a description based on input.
    const designDescription =
      text && text.length > 0
        ? text
        : `Visualized a custom design based on your request: "${input.description}".`;

    return {
      imageUrl: media.url,
      designDescription: designDescription,
    };
  }
);
