import type { Product, Order } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'boho-bliss-rug',
    name: 'Tapete Boho Bliss',
    description: 'Um tapete de estilo boêmio tecido à mão com franjas macias, perfeito para adicionar um toque de aconchego a qualquer ambiente.',
    price: 189.90,
    imageUrl: 'https://picsum.photos/seed/rug1/600/400',
    imageHint: 'bohemian rug',
    category: 'Tapetes Avulsos',
    readyMade: true,
    options: {
      sizes: ['Pequeno (90x150cm)', 'Médio (120x180cm)', 'Grande (150x240cm)'],
      colors: ['Natural', 'Verde Sálvia', 'Rosa Pálido'],
      materials: ['Algodão', 'Lã'],
    },
  },
  {
    id: 'octopus-amigurumi-kit',
    name: 'Kit Amigurumi de Polvo',
    description: 'Crie seu próprio amigo polvo fofinho! Este kit inclui todo o material necessário e um guia passo a passo.',
    price: 79.90,
    imageUrl: 'https://picsum.photos/seed/crochet1/600/400',
    imageHint: 'crochet octopus',
    category: 'Kits de Crochê',
    readyMade: true,
    options: {
      sizes: ['Padrão'],
      colors: ['Azul Oceano', 'Rosa Coral', 'Verde Menta'],
      materials: ['Fio de Algodão'],
    },
  },
  {
    id: 'modern-geometric-rug',
    name: 'Tapete Geométrico Moderno',
    description: 'Linhas limpas e um padrão geométrico arrojado definem este tapete moderno, ideal para espaços contemporâneos.',
    price: 220.50,
    imageUrl: 'https://picsum.photos/seed/rug2/600/400',
    imageHint: 'modern rug',
    category: 'Tapetes Avulsos',
    options: {
      sizes: ['Médio (120x180cm)', 'Grande (150x240cm)'],
      colors: ['Cinza e Branco', 'Preto e Creme', 'Azul Marinho'],
      materials: ['Polipropileno', 'Juta'],
    },
  },
  {
    id: 'sage-round-rug',
    name: 'Tapete Redondo Sálvia',
    description: 'Um tapete de pelúcia redondo em uma suave cor verde sálvia, adicionando conforto e um toque de cor.',
    price: 165.00,
    imageUrl: 'https://picsum.photos/seed/rug3/600/400',
    imageHint: 'green rug',
    category: 'Tapetes Avulsos',
    options: {
      sizes: ['Pequeno (120cm diâmetro)', 'Grande (150cm diâmetro)'],
      colors: ['Verde Sálvia', 'Bege', 'Rosa Pálido'],
      materials: ['Lã', 'Microfibra'],
    },
  },
  {
    id: 'bathroom-mat-set',
    name: 'Jogo de Banheiro Oásis',
    description: 'Um conjunto de 3 peças para banheiro em crochê, com tapete para o vaso, tampa e tapete de saída de banho.',
    price: 155.00,
    imageUrl: 'https://picsum.photos/seed/bath1/600/400',
    imageHint: 'crochet bathroom set',
    category: 'Jogos de Banheiro',
    options: {
      sizes: ['Padrão'],
      colors: ['Azul Petróleo', 'Cinza Chumbo', 'Bege'],
      materials: ['Barbante de Algodão'],
    },
  },
  {
    id: 'table-runner-kit',
    name: 'Kit Jogo Americano Folhas',
    description: 'Faça seu próprio jogo americano de crochê com um lindo padrão de folhas. O kit contém material para 2 peças.',
    price: 110.00,
    imageUrl: 'https://picsum.photos/seed/table1/600/400',
    imageHint: 'crochet placemat',
    category: 'Jogos de Mesa',
    options: {
      sizes: ['Padrão'],
      colors: ['Verde Musgo', 'Mostarda', 'Terracota'],
      materials: ['Fio de Algodão'],
    },
  },
  {
    id: 'chunky-blanket-kit',
    name: 'Kit de Manta Aconchegante',
    description: 'Um kit para iniciantes para criar uma manta de malha grossa super macia. Perfeito para noites frias.',
    price: 150.00,
    imageUrl: 'https://picsum.photos/seed/crochet2/600/400',
    imageHint: 'crochet blanket',
    category: 'Kits de Crochê',
    options: {
      sizes: ['Pequena (100x150cm)', 'Grande (150x200cm)'],
      colors: ['Creme', 'Cinza Claro', 'Verde Sálvia'],
      materials: ['Fio de Chenille'],
    },
  },
  {
    id: 'winter-scarf-kit',
    name: 'Kit Cachecol de Inverno',
    description: 'Um kit fácil de seguir para tricotar um cachecol elegante e quente para o inverno.',
    price: 95.50,
    imageUrl: 'https://picsum.photos/seed/crochet3/600/400',
    imageHint: 'crochet scarf',
    category: 'Kits de Crochê',
    options: {
      sizes: ['Padrão'],
      colors: ['Borgonha', 'Mostarda', 'Carvão'],
      materials: ['Lã Merino'],
    },
  }
];

export const orders: Order[] = [
  {
    id: 'AAB123',
    productId: 'boho-bliss-rug',
    productName: 'Tapete Boho Bliss',
    date: '2024-05-15',
    status: 'Crafting',
    estimatedDelivery: '2024-06-10',
  },
  {
    id: 'AAB124',
    productId: 'chunky-blanket-kit',
    productName: 'Kit de Manta Aconchegante',
    date: '2024-05-20',
    status: 'Shipped',
    trackingNumber: '1Z9999W99999999999',
    estimatedDelivery: '2024-06-01',
  },
  {
    id: 'AAB125',
    productId: 'octopus-amigurumi-kit',
    productName: 'Kit Amigurumi de Polvo',
    date: '2024-05-28',
    status: 'Delivered',
    estimatedDelivery: '2024-05-30',
  },
    {
    id: 'AAB126',
    productId: 'modern-geometric-rug',
    productName: 'Tapete Geométrico Moderno',
    date: '2024-05-29',
    status: 'Processing',
    estimatedDelivery: '2024-06-20',
  },
];
